# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleCalendarDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleCalendarDemo
    pod 'GoogleSignIn'
    pod 'FSCalendar'
    pod 'GoogleAPIClientForREST/Calendar'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire'

end
